Metrics/LineLength:
  Max: 200
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
Style/RegexpLiteral:
  MaxSlashes: 0
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 12
Style/TrivialAccessors:
  Enabled: false
