require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  TargetRailsVersion: 5.2
  ExtraDetails: true
  DisplayStyleGuide: true
  DisplayCopNames: true
  Exclude:
    - tmp/**/*
    - vendor/**/*
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/LineLength:
  Max: 240
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 20
Style/TrivialAccessors:
  Enabled: false
