Metrics/LineLength:
  Max: 200
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 15
Style/TrivialAccessors:
  Enabled: false
