require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  ExtraDetails: true
  DisplayStyleGuide: true
  DisplayCopNames: true
  Exclude:
    - tmp/**/*
    - vendor/**/*
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/LineLength:
  Max: 240
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 20
Style/TrivialAccessors:
  Enabled: false
