language: ruby
rvm:
  - "2.1"
  - "2.0"
cache:
  - bundler
  - apt
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq texlive-full
script:
  - bundle exec rubocop 
  - bundle exec rake spec
  - bundle exec cucumber
