sudo: false
language: ruby
rvm:
  - '2.4'
  - '2.3'
  - '2.2'
  - '2.1'
cache:
  - bundler

before_install:
  - gem install bundler --version 1.14.3 --no-document

script:
  - bundle exec rubocop --version
  - bundle exec rubocop
  - bundle exec indoctrinatr new demo
