language: ruby
rvm:
  - '2.2'
  - '2.1'
  - '2.0'
cache:
  - bundler
  - apt
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq texlive texlive-xetex texlive-latex-extra texlive-generic-extra
  - gem install bundler -v 1.10.6
script:
  - bundle exec rake test_with_coveralls 
