sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6
  - 2.5

before_install:
  - gem install bundler --version=2.0.2 --no-doc
  - gem install bundler-audit --no-doc

script:
  - bundle-audit check --update
  - bundle exec rubocop .
  - bundle exec indoctrinatr new demo
