sudo: true
language: ruby
rvm:
  - '2.2'
  - '2.1'
  - '2.0'
cache:
  - bundler
  - apt
before_install:
  - wget https://github.com/scottkosty/install-tl-ubuntu/raw/master/install-tl-ubuntu && chmod +x ./install-tl-ubuntu && ./install-tl-ubuntu
  - gem install bundler -v 1.10.6
script:
  - bundle exec indoctrinatr demo
  - bundle exec rake test_with_coveralls 
