sudo: false
language: ruby
rvm:
  - '2.5.0'
  - '2.4.3'
  - '2.3.6'
cache: bundler

before_install:
  - gem install bundler --no-document

script:
  - bundle exec rubocop --version
  - bundle exec rubocop --display-cop-names --extra-details 
  - bundle exec indoctrinatr new demo
