sudo: false
language: ruby
rvm:
  - '2.5.1'
  - '2.4.4'
  - '2.3.7'
cache: bundler

before_install:
  - gem install bundler --no-document

script:
  - bundle exec rubocop --version
  - bundle exec rubocop --display-cop-names --extra-details 
  - bundle exec indoctrinatr new demo
